linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - revive
    - unused
    - promlinter
  exclusions:
    rules:
      - path: _test.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      # Exclude `lll` issues for long lines with `go:generate`.
      - linters:
          - lll
        source: "^//go:generate "
