network:
  ping_test:
    interval_seconds: 1
  speedtest:
    interval_minutes: 720
    servers:
      max_ping_timeout: 500ms
      max_servers_to_test: 3

metrics:
  engine: prometheus

logging:
  level: info 
  output_file: /var/log/yanm/yanm.log

debug_server:
  disabled: false
  listen_address: :8090