network:
  speedtest:
    interval_minutes: 1
    servers:
      max_ping_timeout: 500ms
      max_servers_to_test: 3

metrics:
  engine: prometheus

logging:
  level: info
  output_file: /var/log/yanm.log

debug_server:
  enabled: true
  listen_address: :8090