---
# Playbook for deploying YANM (Yet Another Network Monitor)
- name: Deploy YANM
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    yanm_user: "yanm"
    yanm_group: "yanm"

  tasks:
    # Start Docker service
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    # Create yanm group
    - name: Create yanm group
      group:
        name: "{{ yanm_group }}"
        system: yes

    # Create yanm user
    - name: Create yanm user
      user:
        name: "{{ yanm_user }}"
        group: "{{ yanm_group }}"
        system: yes
        createhome: no
        shell: /usr/sbin/nologin

    # Pull Docker image
    - name: Pull Docker image
      docker_image:
        name: ghcr.io/jeffbean/yanm:main
        source: pull
        pull: yes

    # Create container
    - name: Create Docker container
      docker_container:
        name: yanm
        image: ghcr.io/jeffbean/yanm:main
        state: started
        recreate: yes
        restart_policy: unless-stopped
        ports:
          - "8090:8090"
        user: "{{ yanm_user }}"

    # Verify Docker container is running
    - name: Check yanm container status
      docker_container:
        name: yanm
        state: started
      register: container_status

    - name: Show container status
      debug:
        msg: "Container status: {{ container_status.status }}"
