---
# Playbook for deploying YANM (Yet Another Network Monitor)
- name: Deploy YANM
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    yanm_repo: "https://github.com/{{ lookup('env', 'GITHUB_USER') }}/yanm.git"
    yanm_dir: "/opt/yanm"
    yanm_service_name: "yanm"
    yanm_user: "yanm"
    yanm_group: "yanm"
    yanm_config_dir: "/etc/yanm"
    yanm_log_dir: "/var/log/yanm"

  tasks:
    # Create necessary directories
    - name: Create yanm user and group
      user:
        name: "{{ yanm_user }}"
        group: "{{ yanm_group }}"
        system: yes
        createhome: no
        shell: /usr/sbin/nologin

    - name: Create configuration directory
      file:
        path: "{{ yanm_config_dir }}"
        state: directory
        owner: "{{ yanm_user }}"
        group: "{{ yanm_group }}"
        mode: '0755'

    - name: Create log directory
      file:
        path: "{{ yanm_log_dir }}"
        state: directory
        owner: "{{ yanm_user }}"
        group: "{{ yanm_group }}"
        mode: '0755'

    # Git clone/update
    - name: Clone/Update YANM repository
      git:
        repo: "{{ yanm_repo }}"
        dest: "{{ yanm_dir }}"
        update: yes
        force: yes

    # Build the application
    - name: Install Go dependencies
      command: go mod download
      args:
        chdir: "{{ yanm_dir }}"

    - name: Build YANM
      command: go build -o yanm .
      args:
        chdir: "{{ yanm_dir }}"

    # Set up systemd service
    - name: Create yanm.service
      copy:
        content: |
          [Unit]
          Description=Yet Another Network Monitor
          After=network.target

          [Service]
          Type=simple
          User={{ yanm_user }}
          Group={{ yanm_group }}
          WorkingDirectory={{ yanm_dir }}
          ExecStart={{ yanm_dir }}/yanm -config {{ yanm_config_dir }}/config.yml
          Restart=on-failure
          RestartSec=5s
          StandardOutput={{ yanm_log_dir }}/yanm-out.log
          StandardError={{ yanm_log_dir }}/yanm-err.log

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/yanm.service
        owner: root
        group: root
        mode: '0644'

    # Reload systemd and restart service
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Stop yanm service
      systemd:
        name: yanm
        state: stopped

    - name: Start yanm service
      systemd:
        name: yanm
        state: started
        enabled: yes

    # Verify service is running
    - name: Check yanm service status
      systemd:
        name: yanm
        state: started
        enabled: yes
        daemon_reload: yes
      register: service_status

    - name: Show service status
      debug:
        var: service_status
