name: Build and Publish ARM Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to use'
        required: true
        type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Dependencies
        run: |
          go mod download
          go mod tidy 

      - name: Build ARM binary
        run: |
          GOARCH=arm64 GOOS=linux go build -o yanm-linux-arm64 ./cmd/main.go

      - name: Create release tarball
        run: |
          tar -czf yanm-linux-arm64.tar.gz yanm-linux-arm64

      - name: Get tag name
        id: tag
        run: |
          if [ "$GITHUB_EVENT_NAME" = "release" ]; then
            echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "TAG_NAME=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: '*.tar.gz'
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}

      - name: Upload Artifacts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3
        with:
          path: '*.tar.gz'