name: Create Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to use'
        required: true
        type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Dependencies
        run: |
          go mod download
          go mod tidy 

      - name: Build ARM binary
        run: |
          GOARCH=arm64 GOOS=linux go build -o yanm-linux-arm64 ./cmd/main.go

      - name: Create release tarball
        run: |
          tar -czf yanm-linux-arm64.tar.gz yanm-linux-arm64

      - name: Upload Release Assets
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tar.gz'
          tag_name: ${{ github.ref_name }}
          prerelease: true

