name: Build and Publish Binaries

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to use'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
        include:
          - goos: linux
            goarch: amd64
            name: linux-amd64
          - goos: linux
            goarch: arm64
            name: linux-arm64

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Dependencies
        run: |
          go mod download
          go mod tidy 

      - name: Build binary
        run: |
          GOARCH=${{ matrix.goarch }} GOOS=${{ matrix.goos }} go build -o yanm-${{ matrix.name }} ./cmd/main.go

      - name: Create release tarball
        run: |
          tar -czf yanm-${{ matrix.name }}.tar.gz yanm-${{ matrix.name }}

      - name: Upload Release Assets
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: yanm-${{ matrix.name }}.tar.gz
          tag_name: ${{ github.ref_name }}
          prerelease: true
