name: Go Test and Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: |
        go mod download
        go mod tidy

    - name: Run Unit Tests
      run: |
        go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Build Application
      run: |
        go build -v ./...

    - name: Check Go Code Style
      run: |
        go fmt ./...
        go vet ./...

    - name: Run golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
        golangci-lint run --config .golangci.yml

    - name: Upload Coverage Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage.txt
        path: coverage.txt
